---
- name: copying script to remote host
  copy:
    src: '{{ script_name }}'
    dest: '{{ target_dir }}'
    mode: 0755
    force: no


- name: executing script
  command: sh {{ target_dir }}/{{ script_name }} {{ action }}

